// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../frb_generated.dart';

part 'authentication.freezed.dart';
part 'authentication.g.dart';

@freezed
class JwtTokens with _$JwtTokens {
  const factory JwtTokens({
    required String accessToken,
    required String refreshToken,
  }) = _JwtTokens;

  factory JwtTokens.fromJson(Map<String, Object?> json) =>
      _$JwtTokensFromJson(json);
}

@freezed
class LoginData with _$LoginData {
  const factory LoginData({
    required String email,
    required String password,
  }) = _LoginData;

  factory LoginData.fromJson(Map<String, Object?> json) =>
      _$LoginDataFromJson(json);
}

@freezed
class RegisterData with _$RegisterData {
  const factory RegisterData({
    required String name,
    required String email,
    required String password,
    required String rePassword,
  }) = _RegisterData;

  factory RegisterData.fromJson(Map<String, Object?> json) =>
      _$RegisterDataFromJson(json);
}
