// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'financial_cards.freezed.dart';

@freezed
class FinancialCard with _$FinancialCard {
  const factory FinancialCard({
    String? id,
    PlatformInt64? createdAt,
    String? createdBy,
    PlatformInt64? updatedAt,
    String? updatedBy,
    required String cardHolderName,
    required String cardNumber,
    String? cardProviderName,
    String? cardType,
    String? cvv,
    String? expiryDate,
    String? issueDate,
    required String name,
    String? note,
    String? pin,
    bool? isFavorite,
    String? tags,
  }) = _FinancialCard;
}
