// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../models/financial_card_model.dart';
import '../frb_generated.dart';

part 'financial_cards.freezed.dart';
part 'financial_cards.g.dart';

@freezed
class FinancialCard with _$FinancialCard {
  const factory FinancialCard({
    String? id,
    PlatformInt64? createdAt,
    String? createdBy,
    PlatformInt64? updatedAt,
    String? updatedBy,
    required String cardHolderName,
    required String cardNumber,
    String? cardProviderName,
    String? cardType,
    String? cvv,
    String? expiryDate,
    String? issueDate,
    required String name,
    String? note,
    String? pin,
    bool? isFavorite,
    String? tags,
  }) = _FinancialCard;

  factory FinancialCard.fromJson(Map<String, dynamic> json) =>
      _$FinancialCardFromJson(json);

  factory FinancialCard.fromFinancialCardModel(
      FinancialCardModel financialCard) {
    return FinancialCard(
      id: financialCard.id,
      createdAt: financialCard.createdAt,
      createdBy: financialCard.createdBy,
      updatedAt: financialCard.updatedAt,
      updatedBy: financialCard.updatedBy,
      cardHolderName: financialCard.cardHolderName,
      cardNumber: financialCard.cardNumber,
      cardProviderName: financialCard.cardProviderName,
      cardType: financialCard.cardType,
      cvv: financialCard.cvv,
      expiryDate: financialCard.expiryDate,
      issueDate: financialCard.issueDate,
      name: financialCard.name,
      note: financialCard.note,
      pin: financialCard.pin,
      isFavorite: financialCard.isFavorite,
      tags: financialCard.tags?.join(','),
    );
  }
}
