// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'identity_cards.freezed.dart';

@freezed
class IdentityCard with _$IdentityCard {
  const factory IdentityCard({
    String? id,
    PlatformInt64? createdAt,
    String? createdBy,
    PlatformInt64? updatedAt,
    String? updatedBy,
    required String name,
    String? note,
    String? country,
    String? expiryDate,
    required String identityCardNumber,
    String? identityCardType,
    String? issueDate,
    required String nameOnCard,
    String? state,
    bool? isFavorite,
    String? tags,
  }) = _IdentityCard;
}
