// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../models/identity_card_model.dart';
import '../frb_generated.dart';

part 'identity_cards.freezed.dart';
part 'identity_cards.g.dart';

@freezed
class IdentityCard with _$IdentityCard {
  const factory IdentityCard({
    String? id,
    PlatformInt64? createdAt,
    String? createdBy,
    PlatformInt64? updatedAt,
    String? updatedBy,
    required String name,
    String? note,
    String? country,
    String? expiryDate,
    required String identityCardNumber,
    String? identityCardType,
    String? issueDate,
    required String nameOnCard,
    String? state,
    bool? isFavorite,
    String? tags,
  }) = _IdentityCard;

  factory IdentityCard.fromJson(Map<String, dynamic> json) =>
      _$IdentityCardFromJson(json);

  factory IdentityCard.fromIdentityCardModel(IdentityCardModel identityCard) {
    return IdentityCard(
      id: identityCard.id,
      createdAt: identityCard.createdAt,
      createdBy: identityCard.createdBy,
      updatedAt: identityCard.updatedAt,
      updatedBy: identityCard.updatedBy,
      name: identityCard.name,
      note: identityCard.note,
      country: identityCard.country,
      expiryDate: identityCard.expiryDate,
      identityCardNumber: identityCard.identityCardNumber,
      identityCardType: identityCard.identityCardType,
      issueDate: identityCard.issueDate,
      nameOnCard: identityCard.nameOnCard,
      state: identityCard.state,
      isFavorite: identityCard.isFavorite,
      tags: identityCard.tags?.join(','),
    );
  }
}
