// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../models/login_model.dart';
import '../frb_generated.dart';

part 'logins.freezed.dart';
part 'logins.g.dart';

@freezed
class Login with _$Login {
  const factory Login({
    String? id,
    PlatformInt64? createdAt,
    String? createdBy,
    PlatformInt64? updatedAt,
    String? updatedBy,
    required String name,
    String? note,
    required String username,
    String? url,
    String? password,
    String? passwordHint,
    bool? isFavorite,
    String? tags,
    String? apiKeys,
  }) = _Login;

  factory Login.fromJson(Map<String, Object?> json) => _$LoginFromJson(json);

  factory Login.fromLoginModel(LoginModel loginModel) {
    String apiKeys =
        jsonEncode(loginModel.apiKeys?.map((e) => e.toJson()).toList() ?? []);
    return Login(
      name: loginModel.name,
      createdAt: loginModel.createdAt,
      createdBy: loginModel.createdBy,
      updatedAt: loginModel.updatedAt,
      updatedBy: loginModel.updatedBy,
      username: loginModel.username,
      password: loginModel.password,
      passwordHint: loginModel.passwordHint,
      note: loginModel.note,
      url: loginModel.url,
      isFavorite: loginModel.isFavorite,
      tags: loginModel.tags?.join(','),
      apiKeys: apiKeys,
    );
  }
}
