// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../models/note_model.dart';
import '../frb_generated.dart';

part 'notes.freezed.dart';
part 'notes.g.dart';

@freezed
class Note with _$Note {
  const factory Note({
    String? id,
    PlatformInt64? createdAt,
    String? createdBy,
    PlatformInt64? updatedAt,
    String? updatedBy,
    required String name,
    String? note,
    bool? isFavorite,
    String? tags,
  }) = _Note;

  factory Note.fromJson(Map<String, Object?> json) => _$NoteFromJson(json);

  factory Note.fromNoteModel(NoteModel note) {
    return Note(
      id: note.id,
      name: note.name,
      note: note.note,
      isFavorite: note.isFavorite,
      tags: note.tags?.join(','),
      createdAt: note.createdAt,
      createdBy: note.createdBy,
      updatedAt: note.updatedAt,
      updatedBy: note.updatedBy,
    );
  }
}
