GET https://192.168.29.139:8443/api/me HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3Mjg1MTMwNTgsImV4cCI6MTcyODUxMzk1OCwidWlkIjoiMDFKOFBOTTJFSEhDQjlSS1lBWUVWRjk2VkoifQ.X4uPsSXgWUi78abRucKv357cFVTPsb11F5UCf4JLP2M

