[package]
name = "security"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 ="0.5.3"
aes-gcm = "0.10.3"
rand = "0.8.5"
# password-hash = "0.5.0"
base64 = "0.22.1"
# ring = "0.17.8"
thiserror = "2.0.6"
zeroize = "1.8.1"
subtle = "2.4"

[dev-dependencies]
statrs = "0.18.0"
